# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcountry.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form21(object):
    def setupUi(self, Form21):
        Form21.setObjectName("Form21")
        Form21.resize(509, 356)
        self.label_10 = QtWidgets.QLabel(Form21)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 481, 321))
        self.label_10.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(Form21)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 331, 51))
        self.label_2.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form21)
        self.label.setGeometry(QtCore.QRect(90, 20, 321, 51))
        self.label.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Form21)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 239, 16))
        self.label_5.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form21)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 110, 461, 29))
        self.lineEdit_3.setToolTipDuration(-4)
        self.lineEdit_3.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(Form21)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 239, 21))
        self.label_6.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(Form21)
        self.comboBox.setGeometry(QtCore.QRect(20, 170, 461, 31))
        self.comboBox.setToolTipDuration(-1)
        self.comboBox.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(Form21)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 220, 461, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(Form21)
        self.pushButton.setGeometry(QtCore.QRect(20, 220, 461, 41))
        self.pushButton.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form21)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 270, 461, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Form21)
        self.lineEdit.setGeometry(QtCore.QRect(20, 110, 461, 29))
        self.lineEdit.setToolTipDuration(-4)
        self.lineEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form21)
        QtCore.QMetaObject.connectSlotsByName(Form21)

    def retranslateUi(self, Form21):
        _translate = QtCore.QCoreApplication.translate
        Form21.setWindowTitle(_translate("Form21", "Form"))
        self.label_2.setText(_translate("Form21", "<html><head/><body><p align=\"center\">Изменить данные</p></body></html>"))
        self.label.setText(_translate("Form21", "<html><head/><body><p align=\"center\">Добавить страну</p></body></html>"))
        self.label_5.setText(_translate("Form21", "Название:"))
        self.lineEdit_3.setToolTip(_translate("Form21", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_6.setText(_translate("Form21", "Виза:"))
        self.comboBox.setItemText(0, _translate("Form21", "Требуется"))
        self.comboBox.setItemText(1, _translate("Form21", "Не требуется"))
        self.pushButton_3.setText(_translate("Form21", "Изменить"))
        self.pushButton.setText(_translate("Form21", "Добавить"))
        self.pushButton_2.setText(_translate("Form21", "Закрыть"))
        self.lineEdit.setToolTip(_translate("Form21", "<html><head/><body><p>gggg</p></body></html>"))
