# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcl.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form112(object):
    def setupUi(self, Form112):
        Form112.setObjectName("Form112")
        Form112.resize(504, 508)
        self.label = QtWidgets.QLabel(Form112)
        self.label.setGeometry(QtCore.QRect(100, 10, 331, 51))
        self.label.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(Form112)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 481, 481))
        self.label_10.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(Form112)
        self.label_2.setGeometry(QtCore.QRect(100, 0, 331, 71))
        self.label_2.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Form112)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 239, 16))
        self.label_5.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Form112)
        self.lineEdit.setGeometry(QtCore.QRect(20, 90, 461, 29))
        self.lineEdit.setToolTipDuration(-4)
        self.lineEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(Form112)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 239, 21))
        self.label_6.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form112)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 150, 461, 29))
        self.lineEdit_2.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form112)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 210, 461, 29))
        self.lineEdit_4.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(Form112)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 239, 21))
        self.label_7.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_7.setObjectName("label_7")
        self.dateEdit = QtWidgets.QDateEdit(Form112)
        self.dateEdit.setGeometry(QtCore.QRect(20, 274, 461, 31))
        self.dateEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.dateEdit.setObjectName("dateEdit")
        self.label_8 = QtWidgets.QLabel(Form112)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 239, 20))
        self.label_8.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form112)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 340, 461, 29))
        self.lineEdit_5.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(Form112)
        self.label_9.setGeometry(QtCore.QRect(20, 320, 239, 21))
        self.label_9.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form112)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 340, 461, 29))
        self.lineEdit_3.setToolTipDuration(-4)
        self.lineEdit_3.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form112)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 430, 461, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Form112)
        self.pushButton.setGeometry(QtCore.QRect(20, 380, 461, 41))
        self.pushButton.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Form112)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 380, 461, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.lineEdit.raise_()
        self.label_6.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_4.raise_()
        self.label_7.raise_()
        self.dateEdit.raise_()
        self.label_8.raise_()
        self.lineEdit_5.raise_()
        self.label_9.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()

        self.retranslateUi(Form112)
        QtCore.QMetaObject.connectSlotsByName(Form112)

    def retranslateUi(self, Form112):
        _translate = QtCore.QCoreApplication.translate
        Form112.setWindowTitle(_translate("Form112", "Клиенты"))
        self.label.setText(_translate("Form112", "<html><head/><body><p>Добавить клиента</p></body></html>"))
        self.label_2.setText(_translate("Form112", "<html><head/><body><p align=\"center\">Изменить данные</p></body></html>"))
        self.label_5.setText(_translate("Form112", "ФИО:"))
        self.lineEdit.setToolTip(_translate("Form112", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_6.setText(_translate("Form112", "Адрес:"))
        self.lineEdit_2.setToolTip(_translate("Form112", "<html><head/><body><p>gggg</p></body></html>"))
        self.lineEdit_4.setToolTip(_translate("Form112", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_7.setText(_translate("Form112", "Номер телефона:"))
        self.label_8.setText(_translate("Form112", "Дата рождения:"))
        self.lineEdit_5.setToolTip(_translate("Form112", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_9.setText(_translate("Form112", "Паспортные данные:"))
        self.lineEdit_3.setToolTip(_translate("Form112", "<html><head/><body><p>gggg</p></body></html>"))
        self.pushButton_2.setText(_translate("Form112", "Закрыть"))
        self.pushButton.setText(_translate("Form112", "Добавить"))
        self.pushButton_3.setText(_translate("Form112", "Изменить"))
