# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adddisc.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form113(object):
    def setupUi(self, Form113):
        Form113.setObjectName("Form113")
        Form113.resize(501, 315)
        self.label_10 = QtWidgets.QLabel(Form113)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 481, 291))
        self.label_10.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(Form113)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 331, 51))
        self.label_2.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form113)
        self.label.setGeometry(QtCore.QRect(60, 10, 401, 51))
        self.label.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form113)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 90, 461, 29))
        self.lineEdit_3.setToolTipDuration(-4)
        self.lineEdit_3.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Form113)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 239, 16))
        self.label_5.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form113)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 239, 31))
        self.label_6.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form113)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 150, 461, 29))
        self.lineEdit_4.setToolTipDuration(-4)
        self.lineEdit_4.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form113)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 190, 461, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form113)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 240, 461, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Form113)
        self.lineEdit.setGeometry(QtCore.QRect(20, 90, 461, 29))
        self.lineEdit.setToolTipDuration(-4)
        self.lineEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form113)
        self.pushButton.setGeometry(QtCore.QRect(20, 190, 461, 41))
        self.pushButton.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form113)
        QtCore.QMetaObject.connectSlotsByName(Form113)

    def retranslateUi(self, Form113):
        _translate = QtCore.QCoreApplication.translate
        Form113.setWindowTitle(_translate("Form113", "Скидки"))
        self.label_2.setText(_translate("Form113", "<html><head/><body><p align=\"center\">Изменить данные</p></body></html>"))
        self.label.setText(_translate("Form113", "<html><head/><body><p align=\"center\">Добавить тип скидки</p></body></html>"))
        self.lineEdit_3.setToolTip(_translate("Form113", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_5.setText(_translate("Form113", "Тип скидки:"))
        self.label_6.setText(_translate("Form113", "Процент:"))
        self.lineEdit_4.setToolTip(_translate("Form113", "<html><head/><body><p>gggg</p></body></html>"))
        self.pushButton_3.setText(_translate("Form113", "Изменить"))
        self.pushButton_2.setText(_translate("Form113", "Закрыть"))
        self.lineEdit.setToolTip(_translate("Form113", "<html><head/><body><p>gggg</p></body></html>"))
        self.pushButton.setText(_translate("Form113", "Добавить"))
