# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form114(object):
    def setupUi(self, Form114):
        Form114.setObjectName("Form114")
        Form114.resize(504, 614)
        self.label_10 = QtWidgets.QLabel(Form114)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 481, 591))
        self.label_10.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(Form114)
        self.label.setGeometry(QtCore.QRect(120, 10, 281, 51))
        self.label.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form114)
        self.label_2.setGeometry(QtCore.QRect(100, 0, 331, 71))
        self.label_2.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Form114)
        self.comboBox.setGeometry(QtCore.QRect(20, 80, 461, 31))
        self.comboBox.setToolTipDuration(-1)
        self.comboBox.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.label_8 = QtWidgets.QLabel(Form114)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 239, 21))
        self.label_8.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(Form114)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 239, 16))
        self.label_5.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Form114)
        self.lineEdit.setGeometry(QtCore.QRect(20, 140, 301, 29))
        self.lineEdit.setToolTipDuration(-4)
        self.lineEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_7 = QtWidgets.QPushButton(Form114)
        self.pushButton_7.setGeometry(QtCore.QRect(340, 140, 141, 31))
        self.pushButton_7.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_6 = QtWidgets.QLabel(Form114)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 239, 21))
        self.label_6.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_6.setObjectName("label_6")
        self.dateEdit = QtWidgets.QDateEdit(Form114)
        self.dateEdit.setGeometry(QtCore.QRect(20, 200, 461, 31))
        self.dateEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.dateEdit.setObjectName("dateEdit")
        self.label_7 = QtWidgets.QLabel(Form114)
        self.label_7.setGeometry(QtCore.QRect(20, 240, 239, 21))
        self.label_7.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_7.setObjectName("label_7")
        self.dateEdit_2 = QtWidgets.QDateEdit(Form114)
        self.dateEdit_2.setGeometry(QtCore.QRect(20, 260, 461, 31))
        self.dateEdit_2.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_9 = QtWidgets.QLabel(Form114)
        self.label_9.setGeometry(QtCore.QRect(20, 300, 239, 21))
        self.label_9.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(Form114)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 320, 461, 31))
        self.comboBox_2.setToolTipDuration(-1)
        self.comboBox_2.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_11 = QtWidgets.QLabel(Form114)
        self.label_11.setGeometry(QtCore.QRect(20, 360, 239, 21))
        self.label_11.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_11.setObjectName("label_11")
        self.comboBox_3 = QtWidgets.QComboBox(Form114)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 380, 461, 31))
        self.comboBox_3.setToolTipDuration(-1)
        self.comboBox_3.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_12 = QtWidgets.QLabel(Form114)
        self.label_12.setGeometry(QtCore.QRect(20, 420, 239, 21))
        self.label_12.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_12.setObjectName("label_12")
        self.comboBox_4 = QtWidgets.QComboBox(Form114)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 440, 461, 31))
        self.comboBox_4.setToolTipDuration(-1)
        self.comboBox_4.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.pushButton = QtWidgets.QPushButton(Form114)
        self.pushButton.setGeometry(QtCore.QRect(20, 490, 461, 41))
        self.pushButton.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form114)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 540, 461, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form114)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 490, 461, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form114)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 140, 301, 29))
        self.lineEdit_2.setToolTipDuration(-4)
        self.lineEdit_2.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Form114)
        QtCore.QMetaObject.connectSlotsByName(Form114)

    def retranslateUi(self, Form114):
        _translate = QtCore.QCoreApplication.translate
        Form114.setWindowTitle(_translate("Form114", "Form"))
        self.label.setText(_translate("Form114", "<html><head/><body><p>Добавить заказ</p></body></html>"))
        self.label_2.setText(_translate("Form114", "<html><head/><body><p align=\"center\">Изменить данные</p></body></html>"))
        self.label_8.setText(_translate("Form114", "Название тура:"))
        self.label_5.setText(_translate("Form114", "Конечная стоимость:"))
        self.lineEdit.setToolTip(_translate("Form114", "<html><head/><body><p>gggg</p></body></html>"))
        self.pushButton_7.setText(_translate("Form114", "Рассчитать"))
        self.label_6.setText(_translate("Form114", "Дата начала тура:"))
        self.label_7.setText(_translate("Form114", "Дата оплаты тура:"))
        self.label_9.setText(_translate("Form114", "Менеджер:"))
        self.label_11.setText(_translate("Form114", "Клиент:"))
        self.label_12.setText(_translate("Form114", "Скидка:"))
        self.pushButton.setText(_translate("Form114", "Добавить"))
        self.pushButton_2.setText(_translate("Form114", "Закрыть"))
        self.pushButton_3.setText(_translate("Form114", "Изменить"))
        self.lineEdit_2.setToolTip(_translate("Form114", "<html><head/><body><p>gggg</p></body></html>"))
