# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addtour.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form51(object):
    def setupUi(self, Form51):
        Form51.setObjectName("Form51")
        Form51.resize(513, 670)
        self.label_10 = QtWidgets.QLabel(Form51)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 491, 651))
        self.label_10.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(Form51)
        self.label_2.setGeometry(QtCore.QRect(90, 0, 331, 71))
        self.label_2.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form51)
        self.label.setGeometry(QtCore.QRect(140, 10, 241, 51))
        self.label.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form51)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 80, 461, 29))
        self.lineEdit_3.setToolTipDuration(-4)
        self.lineEdit_3.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Form51)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 239, 16))
        self.label_5.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Form51)
        self.lineEdit.setGeometry(QtCore.QRect(30, 80, 461, 29))
        self.lineEdit.setToolTipDuration(-4)
        self.lineEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form51)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 140, 461, 29))
        self.lineEdit_2.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(Form51)
        self.label_6.setGeometry(QtCore.QRect(30, 120, 239, 21))
        self.label_6.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form51)
        self.label_7.setGeometry(QtCore.QRect(30, 180, 239, 21))
        self.label_7.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form51)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 200, 461, 29))
        self.lineEdit_4.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(Form51)
        self.comboBox.setGeometry(QtCore.QRect(30, 260, 461, 31))
        self.comboBox.setToolTipDuration(-1)
        self.comboBox.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(Form51)
        self.label_8.setGeometry(QtCore.QRect(30, 240, 239, 21))
        self.label_8.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form51)
        self.label_9.setGeometry(QtCore.QRect(30, 300, 239, 21))
        self.label_9.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_9.setObjectName("label_9")
        self.comboBox_3 = QtWidgets.QComboBox(Form51)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 380, 461, 31))
        self.comboBox_3.setToolTipDuration(-1)
        self.comboBox_3.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_11 = QtWidgets.QLabel(Form51)
        self.label_11.setGeometry(QtCore.QRect(30, 360, 239, 21))
        self.label_11.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_11.setObjectName("label_11")
        self.comboBox_4 = QtWidgets.QComboBox(Form51)
        self.comboBox_4.setGeometry(QtCore.QRect(30, 440, 461, 31))
        self.comboBox_4.setToolTipDuration(-1)
        self.comboBox_4.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_12 = QtWidgets.QLabel(Form51)
        self.label_12.setGeometry(QtCore.QRect(30, 420, 239, 21))
        self.label_12.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_12.setObjectName("label_12")
        self.comboBox_5 = QtWidgets.QComboBox(Form51)
        self.comboBox_5.setGeometry(QtCore.QRect(30, 500, 461, 31))
        self.comboBox_5.setToolTipDuration(-1)
        self.comboBox_5.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_13 = QtWidgets.QLabel(Form51)
        self.label_13.setGeometry(QtCore.QRect(30, 480, 239, 21))
        self.label_13.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_13.setObjectName("label_13")
        self.pushButton_3 = QtWidgets.QPushButton(Form51)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 550, 461, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form51)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 600, 461, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Form51)
        self.pushButton.setGeometry(QtCore.QRect(30, 550, 461, 41))
        self.pushButton.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.comboBox_2 = QtWidgets.QComboBox(Form51)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 320, 461, 31))
        self.comboBox_2.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")

        self.retranslateUi(Form51)
        QtCore.QMetaObject.connectSlotsByName(Form51)

    def retranslateUi(self, Form51):
        _translate = QtCore.QCoreApplication.translate
        Form51.setWindowTitle(_translate("Form51", "Туры"))
        self.label_2.setText(_translate("Form51", "<html><head/><body><p align=\"center\">Изменить данные</p></body></html>"))
        self.label.setText(_translate("Form51", "<html><head/><body><p>Добавить тур</p></body></html>"))
        self.lineEdit_3.setToolTip(_translate("Form51", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_5.setText(_translate("Form51", "Название:"))
        self.lineEdit.setToolTip(_translate("Form51", "<html><head/><body><p>gggg</p></body></html>"))
        self.lineEdit_2.setToolTip(_translate("Form51", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_6.setText(_translate("Form51", "Количество дней:"))
        self.label_7.setText(_translate("Form51", "Цена:"))
        self.lineEdit_4.setToolTip(_translate("Form51", "<html><head/><body><p>gggg</p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form51", "Нет"))
        self.comboBox.setItemText(1, _translate("Form51", "Да"))
        self.label_8.setText(_translate("Form51", "Горящий тур:"))
        self.label_9.setText(_translate("Form51", "Питание:"))
        self.label_11.setText(_translate("Form51", "Отель"))
        self.label_12.setText(_translate("Form51", "Тип тура:"))
        self.label_13.setText(_translate("Form51", "Страна:"))
        self.pushButton_3.setText(_translate("Form51", "Изменить"))
        self.pushButton_2.setText(_translate("Form51", "Закрыть"))
        self.pushButton.setText(_translate("Form51", "Добавить"))
