# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admchange.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form5(object):
    def setupUi(self, Form5):
        Form5.setObjectName("Form5")
        Form5.resize(463, 445)
        self.label_16 = QtWidgets.QLabel(Form5)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 431, 421))
        self.label_16.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_3 = QtWidgets.QLabel(Form5)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form5)
        self.pushButton.setGeometry(QtCore.QRect(20, 350, 411, 31))
        self.pushButton.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form5)
        self.lineEdit.setGeometry(QtCore.QRect(20, 160, 411, 29))
        self.lineEdit.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(Form5)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 239, 16))
        self.label_5.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form5)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 210, 411, 29))
        self.lineEdit_2.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form5)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 260, 411, 29))
        self.lineEdit_3.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form5)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 310, 411, 29))
        self.lineEdit_4.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(Form5)
        self.label_9.setGeometry(QtCore.QRect(20, 190, 239, 20))
        self.label_9.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(Form5)
        self.label_11.setGeometry(QtCore.QRect(20, 240, 239, 21))
        self.label_11.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_11.setObjectName("label_11")
        self.label_4 = QtWidgets.QLabel(Form5)
        self.label_4.setGeometry(QtCore.QRect(20, 290, 239, 16))
        self.label_4.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form5)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 390, 411, 31))
        self.pushButton_2.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_19 = QtWidgets.QLabel(Form5)
        self.label_19.setGeometry(QtCore.QRect(20, 50, 370, 61))
        self.label_19.setMaximumSize(QtCore.QSize(370, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_19.setText("")
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")

        self.retranslateUi(Form5)
        QtCore.QMetaObject.connectSlotsByName(Form5)

    def retranslateUi(self, Form5):
        _translate = QtCore.QCoreApplication.translate
        Form5.setWindowTitle(_translate("Form5", "Изменение данных"))
        self.label_3.setText(_translate("Form5", "Изменение данных для"))
        self.pushButton.setText(_translate("Form5", "Сохранить"))
        self.lineEdit.setToolTip(_translate("Form5", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_5.setText(_translate("Form5", "ФИО:"))
        self.lineEdit_2.setToolTip(_translate("Form5", "<html><head/><body><p>gggg</p></body></html>"))
        self.lineEdit_3.setToolTip(_translate("Form5", "<html><head/><body><p>gggg</p></body></html>"))
        self.lineEdit_4.setToolTip(_translate("Form5", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_9.setText(_translate("Form5", "Номер телефона:"))
        self.label_11.setText(_translate("Form5", "Адрес проживания:"))
        self.label_4.setText(_translate("Form5", "Семейное положение:"))
        self.pushButton_2.setText(_translate("Form5", "Закрыть"))
