# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(628, 830)
        Form2.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit = QtWidgets.QLineEdit(Form2)
        self.lineEdit.setGeometry(QtCore.QRect(90, 590, 451, 29))
        self.lineEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Form2)
        self.label_3.setGeometry(QtCore.QRect(90, 620, 239, 31))
        self.label_3.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form2)
        self.label.setGeometry(QtCore.QRect(90, 0, 441, 111))
        self.label.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form2)
        self.label_2.setGeometry(QtCore.QRect(90, 570, 239, 16))
        self.label_2.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form2)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 650, 451, 29))
        self.lineEdit_2.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form2)
        self.pushButton.setGeometry(QtCore.QRect(90, 700, 451, 41))
        self.pushButton.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Form2)
        self.label_5.setGeometry(QtCore.QRect(90, 90, 239, 16))
        self.label_5.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form2)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 110, 451, 29))
        self.lineEdit_4.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(Form2)
        self.label_6.setGeometry(QtCore.QRect(90, 146, 239, 20))
        self.label_6.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form2)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 230, 451, 29))
        self.lineEdit_6.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(Form2)
        self.label_7.setGeometry(QtCore.QRect(90, 206, 239, 20))
        self.label_7.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form2)
        self.label_8.setGeometry(QtCore.QRect(90, 270, 239, 16))
        self.label_8.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form2)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 290, 451, 29))
        self.lineEdit_7.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(Form2)
        self.label_9.setGeometry(QtCore.QRect(90, 326, 239, 20))
        self.label_9.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form2)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 350, 451, 29))
        self.lineEdit_8.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_4 = QtWidgets.QLabel(Form2)
        self.label_4.setGeometry(QtCore.QRect(90, 510, 239, 16))
        self.label_4.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(Form2)
        self.comboBox.setGeometry(QtCore.QRect(90, 530, 451, 31))
        self.comboBox.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_10 = QtWidgets.QLabel(Form2)
        self.label_10.setGeometry(QtCore.QRect(70, 10, 491, 791))
        self.label_10.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.dateEdit = QtWidgets.QDateEdit(Form2)
        self.dateEdit.setGeometry(QtCore.QRect(90, 170, 451, 31))
        self.dateEdit.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox_2 = QtWidgets.QComboBox(Form2)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 410, 451, 31))
        self.comboBox_2.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_11 = QtWidgets.QLabel(Form2)
        self.label_11.setGeometry(QtCore.QRect(90, 450, 239, 21))
        self.label_11.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form2)
        self.label_12.setGeometry(QtCore.QRect(90, 390, 239, 16))
        self.label_12.setStyleSheet("font: 13pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_12.setObjectName("label_12")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form2)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 470, 451, 29))
        self.lineEdit_3.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form2)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 750, 451, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_13 = QtWidgets.QLabel(Form2)
        self.label_13.setGeometry(QtCore.QRect(150, 20, 331, 71))
        self.label_13.setStyleSheet("font: 27pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_13.setObjectName("label_13")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form2)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 590, 451, 29))
        self.lineEdit_5.setToolTipDuration(-4)
        self.lineEdit_5.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(75, 75, 75);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_3 = QtWidgets.QPushButton(Form2)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 700, 451, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10.raise_()
        self.lineEdit.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.label_5.raise_()
        self.lineEdit_4.raise_()
        self.label_6.raise_()
        self.lineEdit_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.lineEdit_7.raise_()
        self.label_9.raise_()
        self.lineEdit_8.raise_()
        self.label_4.raise_()
        self.comboBox.raise_()
        self.dateEdit.raise_()
        self.comboBox_2.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_2.raise_()
        self.label_13.raise_()
        self.lineEdit_5.raise_()
        self.pushButton_3.raise_()

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Регистрация"))
        self.lineEdit.setToolTip(_translate("Form2", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_3.setText(_translate("Form2", "Пароль:"))
        self.label.setText(_translate("Form2", "<html><head/><body><p align=\"center\">Регистрация работника</p></body></html>"))
        self.label_2.setText(_translate("Form2", "Логин:"))
        self.pushButton.setText(_translate("Form2", "Зарегистрировать"))
        self.label_5.setText(_translate("Form2", "ФИО:"))
        self.lineEdit_4.setToolTip(_translate("Form2", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_6.setText(_translate("Form2", "Дата рождения:"))
        self.lineEdit_6.setToolTip(_translate("Form2", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_7.setText(_translate("Form2", "Заработная плата"))
        self.label_8.setText(_translate("Form2", "Должность:"))
        self.lineEdit_7.setToolTip(_translate("Form2", "<html><head/><body><p>gggg</p></body></html>"))
        self.label_9.setText(_translate("Form2", "Номер телефона:"))
        self.lineEdit_8.setToolTip(_translate("Form2", "<html><head/><body><p>gggg</p></body></html>"))
        self.lineEdit_8.setPlaceholderText(_translate("Form2", "+7....."))
        self.label_4.setText(_translate("Form2", "Семейное положение"))
        self.comboBox.setItemText(0, _translate("Form2", "Не замужем"))
        self.comboBox.setItemText(1, _translate("Form2", "Не женат"))
        self.comboBox.setItemText(2, _translate("Form2", "Женат"))
        self.comboBox.setItemText(3, _translate("Form2", "Замужем"))
        self.comboBox_2.setItemText(0, _translate("Form2", "USER"))
        self.comboBox_2.setItemText(1, _translate("Form2", "ADMIN"))
        self.label_11.setText(_translate("Form2", "Адрес проживания"))
        self.label_12.setText(_translate("Form2", "Роль"))
        self.lineEdit_3.setToolTip(_translate("Form2", "<html><head/><body><p>gggg</p></body></html>"))
        self.pushButton_2.setText(_translate("Form2", "Закрыть"))
        self.label_13.setText(_translate("Form2", "<html><head/><body><p align=\"center\">Изменить данные</p></body></html>"))
        self.lineEdit_5.setToolTip(_translate("Form2", "<html><head/><body><p>gggg</p></body></html>"))
        self.pushButton_3.setText(_translate("Form2", "Изменить"))
