# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form014(object):
    def setupUi(self, Form014):
        Form014.setObjectName("Form014")
        Form014.resize(1374, 788)
        self.label_20 = QtWidgets.QLabel(Form014)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 1351, 761))
        self.label_20.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.tableWidget = QtWidgets.QTableWidget(Form014)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 1061, 521))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label_4 = QtWidgets.QLabel(Form014)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 141, 61))
        self.label_4.setStyleSheet("font: 25pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(Form014)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 660, 411, 41))
        self.pushButton_4.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form014)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 610, 411, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Form014)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 710, 411, 41))
        self.pushButton_5.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox = QtWidgets.QCheckBox(Form014)
        self.checkBox.setGeometry(QtCore.QRect(1100, 60, 141, 41))
        self.checkBox.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(Form014)
        self.lineEdit.setGeometry(QtCore.QRect(1100, 90, 241, 31))
        self.lineEdit.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox_4 = QtWidgets.QCheckBox(Form014)
        self.checkBox_4.setGeometry(QtCore.QRect(1260, 120, 31, 41))
        self.checkBox_4.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_3 = QtWidgets.QCheckBox(Form014)
        self.checkBox_3.setGeometry(QtCore.QRect(1220, 120, 31, 41))
        self.checkBox_3.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.label = QtWidgets.QLabel(Form014)
        self.label.setGeometry(QtCore.QRect(1100, 130, 81, 21))
        self.label.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.label.setObjectName("label")
        self.checkBox_2 = QtWidgets.QCheckBox(Form014)
        self.checkBox_2.setGeometry(QtCore.QRect(1180, 120, 31, 41))
        self.checkBox_2.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form014)
        self.lineEdit_2.setGeometry(QtCore.QRect(1100, 150, 241, 31))
        self.lineEdit_2.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_5 = QtWidgets.QCheckBox(Form014)
        self.checkBox_5.setGeometry(QtCore.QRect(1100, 180, 141, 41))
        self.checkBox_5.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form014)
        self.lineEdit_3.setGeometry(QtCore.QRect(1100, 210, 241, 31))
        self.lineEdit_3.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox_6 = QtWidgets.QCheckBox(Form014)
        self.checkBox_6.setGeometry(QtCore.QRect(1100, 240, 141, 41))
        self.checkBox_6.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form014)
        self.lineEdit_4.setGeometry(QtCore.QRect(1100, 270, 241, 31))
        self.lineEdit_4.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox_7 = QtWidgets.QCheckBox(Form014)
        self.checkBox_7.setGeometry(QtCore.QRect(1100, 300, 141, 41))
        self.checkBox_7.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form014)
        self.lineEdit_5.setGeometry(QtCore.QRect(1100, 330, 241, 31))
        self.lineEdit_5.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form014)
        self.lineEdit_6.setGeometry(QtCore.QRect(1100, 390, 241, 31))
        self.lineEdit_6.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.checkBox_8 = QtWidgets.QCheckBox(Form014)
        self.checkBox_8.setGeometry(QtCore.QRect(1100, 360, 141, 41))
        self.checkBox_8.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_8.setObjectName("checkBox_8")
        self.pushButton = QtWidgets.QPushButton(Form014)
        self.pushButton.setGeometry(QtCore.QRect(1130, 430, 181, 31))
        self.pushButton.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(Form014)
        self.pushButton_6.setGeometry(QtCore.QRect(820, 680, 271, 31))
        self.pushButton_6.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form014)
        self.pushButton_7.setGeometry(QtCore.QRect(820, 600, 271, 31))
        self.pushButton_7.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(Form014)
        self.pushButton_9.setGeometry(QtCore.QRect(820, 720, 271, 31))
        self.pushButton_9.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(Form014)
        self.pushButton_8.setGeometry(QtCore.QRect(820, 640, 271, 31))
        self.pushButton_8.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(Form014)
        self.pushButton_2.setGeometry(QtCore.QRect(1140, 710, 201, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(Form014)
        self.pushButton_10.setGeometry(QtCore.QRect(450, 610, 311, 81))
        self.pushButton_10.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_10.setObjectName("pushButton_10")

        self.retranslateUi(Form014)
        QtCore.QMetaObject.connectSlotsByName(Form014)

    def retranslateUi(self, Form014):
        _translate = QtCore.QCoreApplication.translate
        Form014.setWindowTitle(_translate("Form014", "Заказы"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form014", "Название тура"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form014", "Конечная стоимость"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form014", "Дата начала"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form014", "Дата оплаты"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form014", "Менеджер"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form014", "Клиент"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form014", "Скидка"))
        self.label_4.setText(_translate("Form014", "Заказы"))
        self.pushButton_4.setText(_translate("Form014", "Изменить выбранную строку"))
        self.pushButton_3.setText(_translate("Form014", "Добавить данные"))
        self.pushButton_5.setText(_translate("Form014", "Удалить выбранную строку"))
        self.checkBox.setText(_translate("Form014", "По названию"))
        self.checkBox_4.setText(_translate("Form014", "="))
        self.checkBox_3.setText(_translate("Form014", "<"))
        self.label.setText(_translate("Form014", "Стоимость"))
        self.checkBox_2.setText(_translate("Form014", ">"))
        self.checkBox_5.setText(_translate("Form014", "Дата начала тура"))
        self.checkBox_6.setText(_translate("Form014", "Дата оплаты тура"))
        self.checkBox_7.setText(_translate("Form014", "Менеджер"))
        self.checkBox_8.setText(_translate("Form014", "Клиент"))
        self.pushButton.setText(_translate("Form014", "Сортировать"))
        self.pushButton_6.setText(_translate("Form014", "Перейти к клиенту"))
        self.pushButton_7.setText(_translate("Form014", "Перейти к туру"))
        self.pushButton_9.setText(_translate("Form014", "Перейти к скидке"))
        self.pushButton_8.setText(_translate("Form014", "Перейти к работнику"))
        self.pushButton_2.setText(_translate("Form014", "Закрыть"))
        self.pushButton_10.setText(_translate("Form014", "Перенести таблицу \n"
"в текстовый документ"))
