# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabletour.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form10(object):
    def setupUi(self, Form10):
        Form10.setObjectName("Form10")
        Form10.resize(1389, 985)
        self.label_20 = QtWidgets.QLabel(Form10)
        self.label_20.setGeometry(QtCore.QRect(20, 10, 1351, 961))
        self.label_20.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.tableWidget = QtWidgets.QTableWidget(Form10)
        self.tableWidget.setGeometry(QtCore.QRect(40, 70, 1061, 721))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label_4 = QtWidgets.QLabel(Form10)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 81, 51))
        self.label_4.setStyleSheet("font: 25pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form10)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 910, 411, 41))
        self.pushButton_5.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(Form10)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 860, 411, 41))
        self.pushButton_4.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form10)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 810, 411, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(Form10)
        self.pushButton.setGeometry(QtCore.QRect(1140, 730, 181, 31))
        self.pushButton.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form10)
        self.pushButton_2.setGeometry(QtCore.QRect(1150, 920, 201, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(Form10)
        self.pushButton_6.setGeometry(QtCore.QRect(830, 890, 271, 31))
        self.pushButton_6.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form10)
        self.pushButton_7.setGeometry(QtCore.QRect(830, 810, 271, 31))
        self.pushButton_7.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form10)
        self.pushButton_8.setGeometry(QtCore.QRect(830, 850, 271, 31))
        self.pushButton_8.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form10)
        self.pushButton_9.setGeometry(QtCore.QRect(830, 930, 271, 31))
        self.pushButton_9.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form10)
        self.lineEdit_7.setGeometry(QtCore.QRect(1110, 450, 241, 31))
        self.lineEdit_7.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.checkBox_12 = QtWidgets.QCheckBox(Form10)
        self.checkBox_12.setGeometry(QtCore.QRect(1110, 420, 141, 41))
        self.checkBox_12.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_12.setObjectName("checkBox_12")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form10)
        self.lineEdit_2.setGeometry(QtCore.QRect(1110, 160, 241, 31))
        self.lineEdit_2.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_4 = QtWidgets.QCheckBox(Form10)
        self.checkBox_4.setGeometry(QtCore.QRect(1310, 130, 31, 41))
        self.checkBox_4.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_10 = QtWidgets.QCheckBox(Form10)
        self.checkBox_10.setGeometry(QtCore.QRect(1110, 360, 141, 41))
        self.checkBox_10.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_10.setObjectName("checkBox_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form10)
        self.lineEdit_3.setGeometry(QtCore.QRect(1110, 220, 241, 31))
        self.lineEdit_3.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox_7 = QtWidgets.QCheckBox(Form10)
        self.checkBox_7.setGeometry(QtCore.QRect(1190, 190, 31, 41))
        self.checkBox_7.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_3 = QtWidgets.QCheckBox(Form10)
        self.checkBox_3.setGeometry(QtCore.QRect(1270, 130, 31, 41))
        self.checkBox_3.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form10)
        self.lineEdit_6.setGeometry(QtCore.QRect(1110, 390, 241, 31))
        self.lineEdit_6.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.checkBox_6 = QtWidgets.QCheckBox(Form10)
        self.checkBox_6.setGeometry(QtCore.QRect(1150, 190, 31, 41))
        self.checkBox_6.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_3 = QtWidgets.QLabel(Form10)
        self.label_3.setGeometry(QtCore.QRect(1110, 270, 91, 21))
        self.label_3.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form10)
        self.lineEdit_4.setGeometry(QtCore.QRect(1110, 330, 241, 31))
        self.lineEdit_4.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox_14 = QtWidgets.QCheckBox(Form10)
        self.checkBox_14.setGeometry(QtCore.QRect(1110, 540, 141, 41))
        self.checkBox_14.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_16 = QtWidgets.QCheckBox(Form10)
        self.checkBox_16.setGeometry(QtCore.QRect(1110, 650, 191, 61))
        self.checkBox_16.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_9 = QtWidgets.QCheckBox(Form10)
        self.checkBox_9.setGeometry(QtCore.QRect(1200, 260, 41, 41))
        self.checkBox_9.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_8 = QtWidgets.QCheckBox(Form10)
        self.checkBox_8.setGeometry(QtCore.QRect(1250, 260, 51, 41))
        self.checkBox_8.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_2 = QtWidgets.QCheckBox(Form10)
        self.checkBox_2.setGeometry(QtCore.QRect(1230, 130, 31, 41))
        self.checkBox_2.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_5 = QtWidgets.QLabel(Form10)
        self.label_5.setGeometry(QtCore.QRect(1110, 490, 91, 21))
        self.label_5.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form10)
        self.lineEdit_8.setGeometry(QtCore.QRect(1110, 570, 241, 31))
        self.lineEdit_8.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form10)
        self.lineEdit_5.setGeometry(QtCore.QRect(1110, 630, 241, 31))
        self.lineEdit_5.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.checkBox_5 = QtWidgets.QCheckBox(Form10)
        self.checkBox_5.setGeometry(QtCore.QRect(1230, 190, 31, 41))
        self.checkBox_5.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox = QtWidgets.QCheckBox(Form10)
        self.checkBox.setGeometry(QtCore.QRect(1110, 70, 141, 41))
        self.checkBox.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_15 = QtWidgets.QCheckBox(Form10)
        self.checkBox_15.setGeometry(QtCore.QRect(1110, 600, 121, 41))
        self.checkBox_15.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_13 = QtWidgets.QCheckBox(Form10)
        self.checkBox_13.setGeometry(QtCore.QRect(1110, 510, 141, 41))
        self.checkBox_13.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_13.setObjectName("checkBox_13")
        self.label_2 = QtWidgets.QLabel(Form10)
        self.label_2.setGeometry(QtCore.QRect(1110, 200, 41, 21))
        self.label_2.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form10)
        self.label.setGeometry(QtCore.QRect(1110, 140, 121, 21))
        self.label.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.label.setObjectName("label")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form10)
        self.lineEdit_9.setGeometry(QtCore.QRect(1110, 690, 241, 31))
        self.lineEdit_9.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.checkBox_11 = QtWidgets.QCheckBox(Form10)
        self.checkBox_11.setGeometry(QtCore.QRect(1110, 300, 141, 41))
        self.checkBox_11.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_11.setObjectName("checkBox_11")
        self.lineEdit = QtWidgets.QLineEdit(Form10)
        self.lineEdit.setGeometry(QtCore.QRect(1110, 100, 241, 31))
        self.lineEdit.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_10 = QtWidgets.QPushButton(Form10)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 810, 411, 41))
        self.pushButton_10.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form10)
        self.pushButton_11.setGeometry(QtCore.QRect(1150, 870, 201, 41))
        self.pushButton_11.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form10)
        self.pushButton_12.setGeometry(QtCore.QRect(460, 810, 311, 91))
        self.pushButton_12.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_12.setObjectName("pushButton_12")

        self.retranslateUi(Form10)
        QtCore.QMetaObject.connectSlotsByName(Form10)

    def retranslateUi(self, Form10):
        _translate = QtCore.QCoreApplication.translate
        Form10.setWindowTitle(_translate("Form10", "Туры"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form10", "Название"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form10", "Количество дней"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form10", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form10", "Горящий тур"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form10", "Питание"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form10", "Отель"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form10", "Тип тура"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form10", "Страна"))
        self.label_4.setText(_translate("Form10", "Туры"))
        self.pushButton_5.setText(_translate("Form10", "Удалить выбранную строку"))
        self.pushButton_4.setText(_translate("Form10", "Изменить выбранную строку"))
        self.pushButton_3.setText(_translate("Form10", "Добавить данные"))
        self.pushButton.setText(_translate("Form10", "Сортировать"))
        self.pushButton_2.setText(_translate("Form10", "Закрыть"))
        self.pushButton_6.setText(_translate("Form10", "Перейти к отелю"))
        self.pushButton_7.setText(_translate("Form10", "Перейти к типам питания"))
        self.pushButton_8.setText(_translate("Form10", "Перейти к типам туров"))
        self.pushButton_9.setText(_translate("Form10", "Перейти к стране"))
        self.checkBox_12.setText(_translate("Form10", "Страна"))
        self.checkBox_4.setText(_translate("Form10", "="))
        self.checkBox_10.setText(_translate("Form10", "Тип тура"))
        self.checkBox_7.setText(_translate("Form10", "<"))
        self.checkBox_3.setText(_translate("Form10", "<"))
        self.checkBox_6.setText(_translate("Form10", ">"))
        self.label_3.setText(_translate("Form10", "Горящий тур"))
        self.checkBox_14.setText(_translate("Form10", "По названию"))
        self.checkBox_16.setText(_translate("Form10", "По количеству звезд"))
        self.checkBox_9.setText(_translate("Form10", "Да"))
        self.checkBox_8.setText(_translate("Form10", "Нет"))
        self.checkBox_2.setText(_translate("Form10", ">"))
        self.label_5.setText(_translate("Form10", "Отель"))
        self.checkBox_5.setText(_translate("Form10", "="))
        self.checkBox.setText(_translate("Form10", "По названию"))
        self.checkBox_15.setText(_translate("Form10", "По городу"))
        self.checkBox_13.setText(_translate("Form10", "Без фильтров"))
        self.label_2.setText(_translate("Form10", "Цена"))
        self.label.setText(_translate("Form10", "Количество дней"))
        self.checkBox_11.setText(_translate("Form10", "Тип питания"))
        self.pushButton_10.setText(_translate("Form10", "Выбрать тур"))
        self.pushButton_11.setText(_translate("Form10", "Далее"))
        self.pushButton_12.setText(_translate("Form10", "Перенести таблицу\n"
"в текстовый документ"))
