# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablecl.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form012(object):
    def setupUi(self, Form012):
        Form012.setObjectName("Form012")
        Form012.resize(1287, 787)
        self.label_20 = QtWidgets.QLabel(Form012)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 1261, 761))
        self.label_20.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.tableWidget = QtWidgets.QTableWidget(Form012)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 971, 521))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label_4 = QtWidgets.QLabel(Form012)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 141, 51))
        self.label_4.setStyleSheet("font: 25pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(Form012)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 660, 411, 41))
        self.pushButton_4.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form012)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 610, 411, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Form012)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 710, 411, 41))
        self.pushButton_5.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(Form012)
        self.pushButton_2.setGeometry(QtCore.QRect(1050, 710, 201, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(Form012)
        self.checkBox.setGeometry(QtCore.QRect(1010, 60, 141, 41))
        self.checkBox.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(Form012)
        self.lineEdit.setGeometry(QtCore.QRect(1010, 90, 241, 31))
        self.lineEdit.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox_2 = QtWidgets.QCheckBox(Form012)
        self.checkBox_2.setGeometry(QtCore.QRect(1010, 120, 141, 41))
        self.checkBox_2.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form012)
        self.lineEdit_2.setGeometry(QtCore.QRect(1010, 150, 241, 31))
        self.lineEdit_2.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form012)
        self.lineEdit_3.setGeometry(QtCore.QRect(1010, 210, 241, 31))
        self.lineEdit_3.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox_3 = QtWidgets.QCheckBox(Form012)
        self.checkBox_3.setGeometry(QtCore.QRect(1010, 180, 141, 41))
        self.checkBox_3.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form012)
        self.lineEdit_4.setGeometry(QtCore.QRect(1010, 270, 241, 31))
        self.lineEdit_4.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox_4 = QtWidgets.QCheckBox(Form012)
        self.checkBox_4.setGeometry(QtCore.QRect(1010, 240, 161, 41))
        self.checkBox_4.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.pushButton = QtWidgets.QPushButton(Form012)
        self.pushButton.setGeometry(QtCore.QRect(1040, 310, 181, 31))
        self.pushButton.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(Form012)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 710, 411, 41))
        self.pushButton_6.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form012)
        self.pushButton_7.setGeometry(QtCore.QRect(1050, 710, 201, 41))
        self.pushButton_7.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form012)
        self.pushButton_8.setGeometry(QtCore.QRect(840, 710, 201, 41))
        self.pushButton_8.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(Form012)
        self.pushButton_10.setGeometry(QtCore.QRect(450, 610, 311, 81))
        self.pushButton_10.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_10.setObjectName("pushButton_10")

        self.retranslateUi(Form012)
        QtCore.QMetaObject.connectSlotsByName(Form012)

    def retranslateUi(self, Form012):
        _translate = QtCore.QCoreApplication.translate
        Form012.setWindowTitle(_translate("Form012", "Клиенты"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form012", "ФИО"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form012", "Адрес"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form012", "Номер телефона"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form012", "Дата рождения"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form012", "Паспортные данные"))
        self.label_4.setText(_translate("Form012", "Клиенты"))
        self.pushButton_4.setText(_translate("Form012", "Изменить выбранную строку"))
        self.pushButton_3.setText(_translate("Form012", "Добавить данные"))
        self.pushButton_5.setText(_translate("Form012", "Удалить выбранную строку"))
        self.pushButton_2.setText(_translate("Form012", "Закрыть"))
        self.checkBox.setText(_translate("Form012", "По ФИО"))
        self.checkBox_2.setText(_translate("Form012", "Номер телефона"))
        self.checkBox_3.setText(_translate("Form012", "Дата рождения"))
        self.checkBox_4.setText(_translate("Form012", "Паспортные данные"))
        self.pushButton.setText(_translate("Form012", "Сортировать"))
        self.pushButton_6.setText(_translate("Form012", "Выбрать клиента"))
        self.pushButton_7.setText(_translate("Form012", "Далее"))
        self.pushButton_8.setText(_translate("Form012", "Закрыть"))
        self.pushButton_10.setText(_translate("Form012", "Перенести таблицу \n"
"в текстовый документ"))
