# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablehotel.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form6(object):
    def setupUi(self, Form6):
        Form6.setObjectName("Form6")
        Form6.resize(1075, 707)
        self.tableWidget = QtWidgets.QTableWidget(Form6)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 761, 451))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(350)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(32)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label_20 = QtWidgets.QLabel(Form6)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 1041, 681))
        self.label_20.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_4 = QtWidgets.QLabel(Form6)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 111, 31))
        self.label_4.setStyleSheet("font: 25pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form6)
        self.pushButton.setGeometry(QtCore.QRect(830, 250, 181, 31))
        self.pushButton.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form6)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 640, 201, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form6)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 540, 411, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form6)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 590, 411, 41))
        self.pushButton_4.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form6)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 640, 411, 41))
        self.pushButton_5.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox = QtWidgets.QCheckBox(Form6)
        self.checkBox.setGeometry(QtCore.QRect(800, 60, 141, 41))
        self.checkBox.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(Form6)
        self.lineEdit.setGeometry(QtCore.QRect(800, 90, 241, 31))
        self.lineEdit.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox_2 = QtWidgets.QCheckBox(Form6)
        self.checkBox_2.setGeometry(QtCore.QRect(800, 120, 121, 41))
        self.checkBox_2.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form6)
        self.lineEdit_2.setGeometry(QtCore.QRect(800, 150, 241, 31))
        self.lineEdit_2.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form6)
        self.checkBox_3.setGeometry(QtCore.QRect(800, 170, 191, 61))
        self.checkBox_3.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form6)
        self.lineEdit_3.setGeometry(QtCore.QRect(800, 210, 241, 31))
        self.lineEdit_3.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_10 = QtWidgets.QPushButton(Form6)
        self.pushButton_10.setGeometry(QtCore.QRect(450, 540, 311, 71))
        self.pushButton_10.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_20.raise_()
        self.tableWidget.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.checkBox.raise_()
        self.lineEdit.raise_()
        self.checkBox_2.raise_()
        self.lineEdit_2.raise_()
        self.checkBox_3.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_10.raise_()

        self.retranslateUi(Form6)
        QtCore.QMetaObject.connectSlotsByName(Form6)

    def retranslateUi(self, Form6):
        _translate = QtCore.QCoreApplication.translate
        Form6.setWindowTitle(_translate("Form6", "Отели"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form6", "Название"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form6", "Город"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form6", "Звездность"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form6", "Дополнительная информация"))
        self.label_4.setText(_translate("Form6", "Отели"))
        self.pushButton.setText(_translate("Form6", "Сортировать"))
        self.pushButton_2.setText(_translate("Form6", "Закрыть"))
        self.pushButton_3.setText(_translate("Form6", "Добавить данные"))
        self.pushButton_4.setText(_translate("Form6", "Изменить выбранную строку"))
        self.pushButton_5.setText(_translate("Form6", "Удалить выбранную строку"))
        self.checkBox.setText(_translate("Form6", "По названию"))
        self.checkBox_2.setText(_translate("Form6", "По городу"))
        self.checkBox_3.setText(_translate("Form6", "По количеству звезд"))
        self.pushButton_10.setText(_translate("Form6", "Перенести таблицу \n"
"в текстовый документ"))
