# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabletourtype.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form9(object):
    def setupUi(self, Form9):
        Form9.setObjectName("Form9")
        Form9.resize(850, 749)
        self.label_20 = QtWidgets.QLabel(Form9)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 831, 721))
        self.label_20.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.tableWidget = QtWidgets.QTableWidget(Form9)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 551, 451))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label_4 = QtWidgets.QLabel(Form9)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 181, 51))
        self.label_4.setStyleSheet("font: 25pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form9)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 530, 411, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Form9)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 630, 411, 41))
        self.pushButton_5.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(Form9)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 580, 411, 41))
        self.pushButton_4.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form9)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 680, 201, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(Form9)
        self.checkBox.setGeometry(QtCore.QRect(590, 60, 141, 41))
        self.checkBox.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(Form9)
        self.lineEdit.setGeometry(QtCore.QRect(590, 90, 241, 31))
        self.lineEdit.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form9)
        self.pushButton.setGeometry(QtCore.QRect(620, 130, 181, 31))
        self.pushButton.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(Form9)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 680, 591, 41))
        self.pushButton_6.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Form9)
        QtCore.QMetaObject.connectSlotsByName(Form9)

    def retranslateUi(self, Form9):
        _translate = QtCore.QCoreApplication.translate
        Form9.setWindowTitle(_translate("Form9", "Типы туров"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form9", "Тип тура"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form9", "Описание"))
        self.label_4.setText(_translate("Form9", "Типы туров"))
        self.pushButton_3.setText(_translate("Form9", "Добавить данные"))
        self.pushButton_5.setText(_translate("Form9", "Удалить выбранную строку"))
        self.pushButton_4.setText(_translate("Form9", "Изменить выбранную строку"))
        self.pushButton_2.setText(_translate("Form9", "Закрыть"))
        self.checkBox.setText(_translate("Form9", "По типу"))
        self.pushButton.setText(_translate("Form9", "Сортировать"))
        self.pushButton_6.setText(_translate("Form9", "Перенести таблицу в текстовый документ"))
