# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabledisc.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form013(object):
    def setupUi(self, Form013):
        Form013.setObjectName("Form013")
        Form013.resize(879, 747)
        self.label_20 = QtWidgets.QLabel(Form013)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 861, 721))
        self.label_20.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.tableWidget = QtWidgets.QTableWidget(Form013)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 581, 451))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label_4 = QtWidgets.QLabel(Form013)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 141, 51))
        self.label_4.setStyleSheet("font: 25pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(Form013)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 580, 411, 41))
        self.pushButton_4.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form013)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 630, 411, 41))
        self.pushButton_5.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3 = QtWidgets.QPushButton(Form013)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 530, 411, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(Form013)
        self.checkBox.setGeometry(QtCore.QRect(620, 60, 141, 41))
        self.checkBox.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(Form013)
        self.lineEdit.setGeometry(QtCore.QRect(620, 90, 241, 31))
        self.lineEdit.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox_2 = QtWidgets.QCheckBox(Form013)
        self.checkBox_2.setGeometry(QtCore.QRect(620, 120, 141, 41))
        self.checkBox_2.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form013)
        self.lineEdit_2.setGeometry(QtCore.QRect(620, 150, 241, 31))
        self.lineEdit_2.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form013)
        self.pushButton.setGeometry(QtCore.QRect(650, 190, 181, 31))
        self.pushButton.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form013)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 680, 201, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(Form013)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 680, 581, 41))
        self.pushButton_10.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_10.setObjectName("pushButton_10")

        self.retranslateUi(Form013)
        QtCore.QMetaObject.connectSlotsByName(Form013)

    def retranslateUi(self, Form013):
        _translate = QtCore.QCoreApplication.translate
        Form013.setWindowTitle(_translate("Form013", "Скидки"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form013", "Тип скидки"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form013", "Процент скидки"))
        self.label_4.setText(_translate("Form013", "Скидки"))
        self.pushButton_4.setText(_translate("Form013", "Изменить выбранную строку"))
        self.pushButton_5.setText(_translate("Form013", "Удалить выбранную строку"))
        self.pushButton_3.setText(_translate("Form013", "Добавить данные"))
        self.checkBox.setText(_translate("Form013", "По типу"))
        self.checkBox_2.setText(_translate("Form013", "Процент"))
        self.pushButton.setText(_translate("Form013", "Сортировать"))
        self.pushButton_2.setText(_translate("Form013", "Закрыть"))
        self.pushButton_10.setText(_translate("Form013", "Перенести таблицу в текстовый документ"))
