# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablefood.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form8(object):
    def setupUi(self, Form8):
        Form8.setObjectName("Form8")
        Form8.resize(874, 748)
        self.label_20 = QtWidgets.QLabel(Form8)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 851, 731))
        self.label_20.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.tableWidget = QtWidgets.QTableWidget(Form8)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 581, 451))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label_4 = QtWidgets.QLabel(Form8)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 141, 51))
        self.label_4.setStyleSheet("font: 25pt \"Century Gothic\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 158, 88);")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(Form8)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 580, 411, 41))
        self.pushButton_4.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form8)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 630, 411, 41))
        self.pushButton_5.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3 = QtWidgets.QPushButton(Form8)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 530, 411, 41))
        self.pushButton_3.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(Form8)
        self.checkBox.setGeometry(QtCore.QRect(620, 60, 141, 41))
        self.checkBox.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(Form8)
        self.lineEdit.setGeometry(QtCore.QRect(620, 90, 241, 31))
        self.lineEdit.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form8)
        self.pushButton.setGeometry(QtCore.QRect(650, 130, 181, 31))
        self.pushButton.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form8)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 680, 201, 41))
        self.pushButton_2.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(Form8)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 680, 591, 41))
        self.pushButton_10.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"border-width: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 158, 88);")
        self.pushButton_10.setObjectName("pushButton_10")

        self.retranslateUi(Form8)
        QtCore.QMetaObject.connectSlotsByName(Form8)

    def retranslateUi(self, Form8):
        _translate = QtCore.QCoreApplication.translate
        Form8.setWindowTitle(_translate("Form8", "Питание"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form8", "Тип питания"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form8", "Описание"))
        self.label_4.setText(_translate("Form8", "Питание"))
        self.pushButton_4.setText(_translate("Form8", "Изменить выбранную строку"))
        self.pushButton_5.setText(_translate("Form8", "Удалить выбранную строку"))
        self.pushButton_3.setText(_translate("Form8", "Добавить данные"))
        self.checkBox.setText(_translate("Form8", "По типу"))
        self.pushButton.setText(_translate("Form8", "Сортировать"))
        self.pushButton_2.setText(_translate("Form8", "Закрыть"))
        self.pushButton_10.setText(_translate("Form8", "Перенести таблицу в текстовый документ"))
